version: "3"
services:
  db:
    image: mariadb:10.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    ports:
      - "8101:3306"
    networks:
    - relative-pitch-training2-network

  web:
    build:
      context: ./relative-pitch-training-api
      dockerfile: ./Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./relative-pitch-training-api:/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 8102:3000
    networks:
      - relative-pitch-training2-network
    depends_on:
      - db
    tty: true
    stdin_open: true

  # front:
  #   build: .
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=8000
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - relative-pitch-training2-network
  #   tty: true
  #   command: sh -c 'npm start'
  deploy:
    build:
      context: ./build
    volumes:
      - ./:/usr/src/app
    image: python:3.13.0a4-alpine3.19
    ports:
      - 8100:8000
    command: sh -c "cd /usr/src/app/build && python -m http.server 8000"

volumes:
  bundle-volume:
  db-data:

networks:
  relative-pitch-training2-network:
    external: true
