import Note from "../enums/Note"

const dict: { [key: string]: string } = {
    [Note.A0]: "A0",
    [Note.ASharp0]: "A#0",
    [Note.B0]: "B0",
    [Note.C1]: "C1",
    [Note.CSharp1]: "C#1",
    [Note.D1]: "D1",
    [Note.DSharp1]: "D#1",
    [Note.E1]: "E1",
    [Note.F1]: "F1",
    [Note.FSharp1]: "F#1",
    [Note.G1]: "G1",
    [Note.GSharp1]: "G#1",
    [Note.A1]: "A1",
    [Note.ASharp1]: "A#1",
    [Note.B1]: "B1",
    [Note.C2]: "C2",
    [Note.CSharp2]: "C#2",
    [Note.D2]: "D2",
    [Note.DSharp2]: "D#2",
    [Note.E2]: "E2",
    [Note.F2]: "F2",
    [Note.FSharp2]: "F#2",
    [Note.G2]: "G2",
    [Note.GSharp2]: "G#2",
    [Note.A2]: "A2",
    [Note.ASharp2]: "A#2",
    [Note.B2]: "B2",
    [Note.C3]: "C3",
    [Note.CSharp3]: "C#3",
    [Note.D3]: "D3",
    [Note.DSharp3]: "D#3",
    [Note.E3]: "E3",
    [Note.F3]: "F3",
    [Note.FSharp3]: "F#3",
    [Note.G3]: "G3",
    [Note.GSharp3]: "G#3",
    [Note.A3]: "A3",
    [Note.ASharp3]: "A#3",
    [Note.B3]: "B3",
    [Note.C4]: "C4",
    [Note.CSharp4]: "C#4",
    [Note.D4]: "D4",
    [Note.DSharp4]: "D#4",
    [Note.E4]: "E4",
    [Note.F4]: "F4",
    [Note.FSharp4]: "F#4",
    [Note.G4]: "G4",
    [Note.GSharp4]: "G#4",
    [Note.A4]: "A4",
    [Note.ASharp4]: "A#4",
    [Note.B4]: "B4",
    [Note.C5]: "C5",
    [Note.CSharp5]: "C#5",
    [Note.D5]: "D5",
    [Note.DSharp5]: "D#5",
    [Note.E5]: "E5",
    [Note.F5]: "F5",
    [Note.FSharp5]: "F#5",
    [Note.G5]: "G5",
    [Note.GSharp5]: "G#5",
    [Note.A5]: "A5",
    [Note.ASharp5]: "A#5",
    [Note.B5]: "B5",
    [Note.C6]: "C6",
    [Note.CSharp6]: "C#6",
    [Note.D6]: "D6",
    [Note.DSharp6]: "D#6",
    [Note.E6]: "E6",
    [Note.F6]: "F6",
    [Note.FSharp6]: "F#6",
    [Note.G6]: "G6",
    [Note.GSharp6]: "G#6",
    [Note.A6]: "A6",
    [Note.ASharp6]: "A#6",
    [Note.B6]: "B6",
    [Note.C7]: "C7",
    [Note.CSharp7]: "C#7",
    [Note.D7]: "D7",
    [Note.DSharp7]: "D#7",
    [Note.E7]: "E7",
    [Note.F7]: "F7",
    [Note.FSharp7]: "F#7",
    [Note.G7]: "G7",
    [Note.GSharp7]: "G#7",
    [Note.A7]: "A7",
    [Note.ASharp7]: "A#7",
    [Note.B7]: "B7",
    [Note.C8]: "C8",
    [Note.CSharp8]: "C#8",
    [Note.D8]: "D8",
    [Note.DSharp8]: "D#8",
    [Note.E8]: "E8",
    [Note.F8]: "F8",
    [Note.FSharp8]: "F#8",
    [Note.G8]: "G8",
    [Note.GSharp8]: "G#8",
    [Note.A8]: "A8",
    [Note.ASharp8]: "A#8",
    [Note.B8]: "B8",
    [Note.C9]: "C9",
};

export default function getNoteName(note: Note): string {
    if (dict[note] === undefined) {
        throw new Error(`Unexpected note: ${note}`);
    }

    return dict[note];
}
